name: gen-traffic

on:
  schedule:
    - cron: "*/10 * * * *" # ทำงานทุก 10 นาที

jobs:
  gen-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate traffic
        run: |
          while true; do
            N=$(shuf -i 1-100 -n 1)
            echo "Making ${N} random requests"
            shuf -n ${N} urls.txt | xargs -I {} bash -c "curl {} -o /dev/null; sleep 1;" || true
            sleep 5
          done
